services:
  - type: web
    name: demo-spring-boot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: demo-postgres
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: demo-postgres
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: demo-postgres
          property: password
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /actuator/health

databases:
  - name: demo-postgres
    databaseName: demodb
    user: postgres
    plan: free
